# Generated by Django 4.2.9 on 2024-01-17 21:36

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('mobile', models.CharField(blank=True, error_messages={'unique': 'A user with that mobile number already exists.'}, help_text='Required. 12 digits including country code', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='length12', message='Length has to be 12', regex='^.{12}$'), django.core.validators.RegexValidator(code='CountryCode', message='Country Code should be allowed', regex='^(98)(\\d{10})$'), django.core.validators.MinLengthValidator(12, message='It should be at least 12 chars')])),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'indexes': [models.Index(fields=['mobile'], name='authenticat_mobile_b06c4c_idx'), models.Index(fields=['email'], name='authenticat_email_d74434_idx')],
            },
        ),
    ]
